spring:
  config:
    import: # Import environment variables from .env._____ files
      - optional:file:keycloak.env[.properties]
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}  # Keycloak issuer URI
            user-name-attribute: preferred_username  # Attribute to use for username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}  # Keycloak client ID
            client-secret: ${KEYCLOAK_CLIENT_SECRET}  # Keycloak client secret
            scope:
              - openid  # Scopes for OAuth2