version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - postgres_minio_network
      - external_keycloak_network

  postgres:
    image: postgres:15-alpine
    container_name: minio-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_minio_network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  minio-data:
  postgres-data:
  redis-data:

networks:
  postgres_minio_network:
    driver: bridge
  redis-network:
  external_keycloak_network:
    name: external_keycloak_network